### PR TITLE
bugfix: Unable to geocode destination address to coordinates: Index 0 out of range [0..0) error (Android) #281

### PR DESCRIPTION
**Pull request by ryaa**
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [ ] Other... Please describe:

## PR Checklist
For bug fixes / features, please check if your PR fulfills the following requirements:

- [x] Testing has been carried out for the changes have been added
- [x] Regression testing has been carried out for existing functionality
- [ ] Docs have been added / updated

## What is the purpose of this PR?

Correctly handle the geocoding returning no results and fix this issue https://github.com/dpa99c/phonegap-launch-navigator/issues/281

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## What testing has been done on the changes in the PR?
Tested the fix in my local project.

## What testing has been done on existing functionality?
Tested the fix in my local project.

## Other information
For more details please see https://github.com/dpa99c/phonegap-launch-navigator/issues/281

### CODE REVIEW

**Comment by ryaa** [comment]
Sorry. I had to fix the minor typo in the original PR - see https://github.com/dpa99c/phonegap-launch-navigator/pull/283

**Comment by dpa99c** [comment]
no worries, it's merged

**Comment by ryaa** [comment]
@dpa99c any plans to release new version with the above fix?

**Comment by dpa99c** [comment]
Sorry, thought I had released it. I'll publish it in a patch version now.

**Comment by dpa99c** [comment]
published as `uk.co.workingedge.phonegap.plugin.launchnavigator@5.0.7`

**Pull request merged**
