### PR TITLE
Fix enum naming collision

### LINKED ISSUE #258: Issues with Xcode 12.3 / Redefinition of enumerator & Expected identifier or '('
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/phonegap-launch-navigator#reporting-issues)
- [X] I confirm this is a suspected bug or issue that will affect other users
- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) or provided the necessary information to reproduce the issue.
- [X] I have read [the documentation](https://github.com/dpa99c/phonegap-launch-navigator) thoroughly and it does not help solve my issue.
- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

```
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:15:5: redefinition of enumerator 'NotReachable'
    NotReachable = 0,
        ^
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:16:5: redefinition of enumerator 'ReachableViaWiFi'
    ReachableViaWiFi,
        ^
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:17:5: redefinition of enumerator 'ReachableViaWWAN'
    ReachableViaWWAN
        ^
❌  /Users/vagrant/git/ios/capacitor-cordova-ios-plugins/sources/Uk.co.workingedge.phonegap.plugin.launchnavigator/LN_Reachability.h:24:18: expected identifier or '('
extern NSString *kReachabilityChangedNotification;
```

_iOS build issue:_
- Node JS version
    - 14
- XCode version
    - Xcode 12.3 (Build version 12C33)

There was an issue in the past with the redefinition thing.
#248 #251

When I have time I'll fix this issue here, too.

### PR DESCRIPTION
**Pull request by blhylton**
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [ ] Other... Please describe:

## PR Checklist
For bug fixes / features, please check if your PR fulfills the following requirements:

- [x] Testing has been carried out for the changes have been added
- [x] Regression testing has been carried out for existing functionality
- [x] Docs have been added / updated

## What is the purpose of this PR?

Resolves #258 

- Prefixes enum names with LN
- Changes declared variable name in the header file to match implementation

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## What testing has been done on the changes in the PR?

Allows apps using this plugin with newer XCode versions to compile and function correctly

## What testing has been done on existing functionality?

No changes to functionality; Purely a refactor.

## Other information

### CODE REVIEW

**Comment by j3gb3rt** [comment]
@dpa99c I have seen the issue fixed by this PR on both xcode 12.0.1 and xcode 12.3. Manually applying this patch fixed it for us. Would love to get this via an update instead of having to use the patch as a workaround. I know you do this in your free time. The plugin is awesome! Keep it up 👍

**Comment by j3gb3rt** [comment]
@blhylton Actually I installed this commit directly with npm and found there are a few instances that didn't get updated with the new enums. Lines 182, 197, and 206. I've updated them below

```
if ((flags & kSCNetworkReachabilityFlagsConnectionRequired) == 0)
    {
        /*
         If the target host is reachable and no connection is required then we'll assume (for now) that you're on Wi-Fi...
         */
        returnValue = LN_ReachableViaWiFi;
    }

    if ((((flags & kSCNetworkReachabilityFlagsConnectionOnDemand ) != 0) ||
        (flags & kSCNetworkReachabilityFlagsConnectionOnTraffic) != 0))
    {
        /*
         ... and the connection is on-demand (or on-traffic) if the calling application is using the CFSocketStream or higher APIs...
         */

        if ((flags & kSCNetworkReachabilityFlagsInterventionRequired) == 0)
        {
            /*
             ... and no [user] intervention is needed...
             */
            returnValue = LN_ReachableViaWiFi;
        }
    }

    if ((flags & kSCNetworkReachabilityFlagsIsWWAN) == kSCNetworkReachabilityFlagsIsWWAN)
    {
        /*
         ... but WWAN connections are OK if the calling application is using the CFNetwork APIs.
         */
        returnValue = LN_ReachableViaWWAN;
    }
```

**Comment by blhylton** [comment]
@j3gb3rt Good catch. I've updated the PR.

**Comment by j3gb3rt** [comment]
@dpa99c Just bumping this. Everything seems to be good here and it's just a small refactor. Using a custom branch of this right now (so no rush from me), but might help others

**Pull request merged**
